name: "build user config"
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - "boards/shields/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
